# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Deploy to Firebase Hosting"
description: "A GitHub Action to deploy to Firebase Hosting"
author: "Jason Miller (https://github.com/developit) and Firebase"
branding:
  icon: "globe"
  color: "blue"
runs:
  using: "node12"
  main: "bin/action.min.js"
inputs:
  repoToken:
    description: "The GITHUB_TOKEN secret"
    required: false
  firebaseServiceAccount:
    description: "Firebase service account JSON"
    required: false
  firebaseToken:
    description: "Firebase token"
    required: false

  expires:
    description: "How long should a preview live? See the preview channels docs for options"
    default: "7d"
    required: false

  projectId:
    description:
      "The project to deploy to. If you leave this blank, make sure you check in
      a .firebaserc file"
    required: false
  channelId:
    description:
      "The preview channel id to deploy to. If you leave this blank, an channel
      id will be auto-generated per branch or PR"
    required: false
  targets:
    description: "Comma-separated list of targets to deploy to"
    required: false

  entryPoint:
    description:
      "The location of your firebase.json file, relative to the root of your
      directory"
    default: "."
    required: false

  # these are only required if you're running outside of the pull_request target.
  prNumber:
    description: PR number
    required: false
  prBranchName:
    description: PR branch name
    required: false
  commitSHA:
    description: Commit SHA of the commit that triggered this
    required: false

outputs:
  urls:
    description: The url(s) deployed to
  expire_time:
    description: The time the deployed preview urls expire
  details_url:
    description: A single URL that was deployed to
